### ISSUE TITLE
Bug in calls to _split2?

### ISSUE THREAD

**Issue by hakanai** [dmgbuild/ds_store#14]
The code at the top of split2 takes only elements 0 and 1, as if it assumes the list is always length 2:

https://github.com/dmgbuild/ds_store/blob/main/src/ds_store/store.py#L474-L476

But then code inside _rebalance seems to pass in a list of length 3:

https://github.com/dmgbuild/ds_store/blob/main/src/ds_store/store.py#L884-L893

Does this actually work? I notice the tests for this library are fairly sparse.

**Comment by freakboy3742** [comment]
I believe this is intentional. The comment previous indicates that it's a speculative split; the 2-part split is done, and if there's no pivots, then the rebalancing can be shortcut. If a pivot *is* found, a full 3-part split is performed.

Agreed that the tests are fairly sparse; it would definitely be desirable to have more (... are you volunteering? :-). However, unless you're seeing a specific issue, I'm going to close this as being not an issue.

**Comment by hakanai** [comment]
If I had more test data, I'd be tempted to do it. Getting test data though has been my entire problem. (I'm trying to implement something similar on JVM.)
